export const GET_ALL_POSTS= "GET_ALL_POSTS"
export const GET_ALL_NOSOTROS = "GET_ALL_NOSOTROS"
export const GET_ALL_SERVICIOS = "ET_ALL_SERVICIOS"
export const GET_ALL_PRODUCTOS = "ET_ALL_PRODUCTOS"
export const GET_ALL_CONTACTOS = "ET_ALL_CONTACTOS"


// accciones individuales

export const GET_POST = "GET_POST"
export const GET_SERVICIO = 'GET_SERVICIO'
export const GET_PRODUCTO = "GET_PRODUCTO"
export const GET_CONTACTO = "GET_CONTACTO"

//DASHBOARD

export const GET_USUARIOS="GET_USUARIOS"
export const GET_USUARIO="GET_USUARIO"
export const POST_USUARIO="POST_USUARIO"
export const PUT_USUARIO="PUT_USUARIO"
export const DEL_USUARIO="DEL_USUARIO"
