export const GET_ALL_POSTS= "GET_ALL_POSTS"
export const GET_ALL_NOSOTROS = "GET_ALL_NOSOTROS"
export const GET_ALL_SERVICIOS = "ET_ALL_SERVICIOS"
export const GET_ALL_PRODUCTOS = "ET_ALL_PRODUCTOS"
export const GET_ALL_CONTACTOS = "ET_ALL_CONTACTOS"


// accciones individuales

export const GET_POST = "GET_POST"
export const GET_SERVICIO = 'GET_SERVICIO'
export const GET_PRODUCTO = "GET_PRODUCTO"
export const GET_CONTACTO = "GET_CONTACTO"

//DASHBOARD

//USUARIO
export const GET_USUARIOS="GET_USUARIOS"
export const GET_USUARIO="GET_USUARIO"
export const POST_USUARIO="POST_USUARIO"
export const PUT_USUARIO="PUT_USUARIO"
export const DEL_USUARIO="DEL_USUARIO"

//CATEGORIA
export const GET_CATEGORIAS="GET_CATEGORIAS"
export const GET_CATEGORIA="GET_CATEGORIA"
export const POST_CATEGORIA="POST_CATEGORIA"
export const PUT_CATEGORIA="PUT_CATEGORIA"
export const DEL_CATEGORIA="DEL_CATEGORIA"

//CITA
export const GET_CITAS="GET_CITAS"
export const GET_CITA="GET_CITA"
export const POST_CITA="POST_CITA"
export const PUT_CITA="PUT_CITA"
export const DEL_CITA="DEL_CITA"

//CLIENTE
export const GET_CLIENTES="GET_CLIENTES"
export const GET_CLIENTE="GET_CLIENTE"
export const POST_CLIENTE="POST_CLIENTE"
export const PUT_CLIENTE="PUT_CLIENTE"
export const DEL_CLIENTE="DEL_CLIENTE"

//ESPECIE
export const GET_ESPECIES="GET_ESPECIES"
export const GET_ESPECIE="GET_ESPECIE"
export const POST_ESPECIE="POST_ESPECIE"
export const PUT_ESPECIE="PUT_ESPECIE"
export const DEL_ESPECIE="DEL_ESPECIE"

//FACTURA
export const GET_FACTURAS="GET_FACTURAS"
export const GET_FACTURA="GET_FACTURA"
export const POST_FACTURA="POST_FACTURA"
export const PUT_FACTURA="PUT_FACTURA"
export const DEL_FACTURA="DEL_FACTURA"

//HISTORIA_CLINICA
export const GET_HISTORIA_CLINICAS="GET_HISTORIA_CLINICAS"
export const GET_HISTORIA_CLINICA="GET_HISTORIA_CLINICA"
export const POST_HISTORIA_CLINICA="POST_HISTORIA_CLINICA"
export const PUT_HISTORIA_CLINICA="PUT_HISTORIA_CLINICA"
export const DEL_HISTORIA_CLINICA="DEL_HISTORIA_CLINICA"

//MASCOTA
export const GET_MASCOTAS="GET_MASCOTAS"
export const GET_MASCOTA="GET_MASCOTA"
export const POST_MASCOTA="POST_MASCOTA"
export const PUT_MASCOTA="PUT_MASCOTA"
export const DEL_MASCOTA="DEL_MASCOTA"

//PROVEEDOR
export const GET_PROVEEDORS="GET_PROVEEDORS"
export const GET_PROVEEDOR="GET_PROVEEDOR"
export const POST_PROVEEDOR="POST_PROVEEDOR"
export const PUT_PROVEEDOR="PUT_PROVEEDOR"
export const DEL_PROVEEDOR="DEL_PROVEEDOR"

//RECETA
export const GET_RECETAS="GET_RECETAS"
export const GET_RECETA="GET_RECETA"
export const POST_RECETA="POST_RECETA"
export const PUT_RECETA="PUT_RECETA"
export const DEL_RECETA="DEL_RECETA"

//ROL
export const GET_ROLS="GET_ROLS"
export const GET_ROL="GET_ROL"
export const POST_ROL="POST_ROL"
export const PUT_ROL="PUT_ROL"
export const DEL_ROL="DEL_ROL"

//PLANTILLA
/*
NO BORRAR PARA CREAR MAS EN AUTOMATICO
export const GET_PLANTILLAS="GET_PLANTILLAS"
export const GET_PLANTILLA="GET_PLANTILLA"
export const POST_PLANTILLA="POST_PLANTILLA"
export const PUT_PLANTILLA="PUT_PLANTILLA"
export const DEL_PLANTILLA="DEL_PLANTILLA"
*/