import { combineReducers, createStore, applyMiddleware } from "redux"
import { composeWithDevTools } from "redux-devtools-extension"
import thunk from "redux-thunk"
import {
  postReducer,
  nosotrosReducer,
  serviciosReducer,
  productosReducer,
  contactosReducer,
  postUser as postUserState,
  getUsuarios as UsuariosState,
  deleteUsuario as deleteUsuarioState,
  putUsuario as putUsuarioState,
  getUsuario as UsuarioState,

  postCategoria as postCategoriaState,
  getCategorias as CategoriasState,
  deleteCategoria as deleteCategoriaState,
  putCategoria as putCategoriaState,
  getCategoria as CategoriaState,

  postCita as postCitaState,
  getCitas as CitasState,
  deleteCita as deleteCitaState,
  putCita as putCitaState,
  getCita as CitaState,

  postCliente as postClienteState,
  getClientes as ClientesState,
  deleteCliente as deleteClienteState,
  putCliente as putClienteState,
  getCliente as ClienteState,

  postEspecie as postEspecieState,
  getEspecies as EspeciesState,
  deleteEspecie as deleteEspecieState,
  putEspecie as putEspecieState,
  getEspecie as EspecieState,

  postFactura as postFacturaState,
  getFacturas as FacturasState,
  deleteFactura as deleteFacturaState,
  putFactura as putFacturaState,
  getFactura as FacturaState,

  postHistoria_clinica as postHistoria_clinicaState,
  getHistoria_clinicas as Historia_clinicasState,
  deleteHistoria_clinica as deleteHistoria_clinicaState,
  putHistoria_clinica as putHistoria_clinicaState,
  getHistoria_clinica as Historia_clinicaState,

  postMascota as postMascotaState,
  getMascotas as MascotasState,
  deleteMascota as deleteMascotaState,
  putMascota as putMascotaState,
  getMascota as MascotaState,
  
  postReceta as postRecetaState,
  getRecetas as RecetasState,
  deleteReceta as deleteRecetaState,
  putReceta as putRecetaState,
  getReceta as RecetaState,

  
  postProveedor as postProveedorState,
  getProveedors as ProveedorsState,
  deleteProveedor as deleteProveedorState,
  putProveedor as putProveedorState,
  getProveedor as ProveedorState,
  
  postRol as postRolState,
  getRols as RolsState,
  deleteRol as deleteRolState,
  putRol as putRolState,
  getRol as RolState,

  postProducto as postProductoState,
  getProductos as ProductosState,
  deleteProducto as deleteProductoState,
  putProducto as putProductoState,
  getProducto as ProductoState,
  /*
  NO BORRAR LA PsLANTILLA
  postPslantilla as postPslantillaState,
  getPslantillas as PslantillasState,
  deletePslantilla as deletePslantillaState,
  putPslantilla as putPslantillaState,
  getPslantilla as PslantillaState,
  */
} from "./reducers"

export default createStore(
  combineReducers({
    postReducer,
    nosotrosReducer,
    serviciosReducer,
    productosReducer,
    contactosReducer,
    postUserState,
    UsuariosState,
    deleteUsuarioState,
    putUsuarioState,
    UsuarioState,
    postCategoriaState,
    CategoriasState,
    deleteCategoriaState,
    putCategoriaState,
    CategoriaState,
    postCitaState,
    CitasState,
    deleteCitaState,
    putCitaState,
    CitaState,
    postClienteState,
    ClientesState,
    deleteClienteState,
    putClienteState,
    ClienteState,
    postEspecieState,
    EspeciesState,
    deleteEspecieState,
    putEspecieState,
    EspecieState,
    postFacturaState,
    FacturasState,
    deleteFacturaState,
    putFacturaState,
    FacturaState,
    postHistoria_clinicaState,
    Historia_clinicasState,
    deleteHistoria_clinicaState,
    putHistoria_clinicaState,
    Historia_clinicaState,
    postMascotaState,
    MascotasState,
    deleteMascotaState,
    putMascotaState,
    MascotaState,
    postProveedorState,
    ProveedorsState,
    deleteProveedorState,
    putProveedorState,
    ProveedorState,
    postRecetaState,
    RecetasState,
    deleteRecetaState,
    putRecetaState,
    RecetaState,
    postRolState,
    RolsState,
    deleteRolState,
    putRolState,
    RolState,
    ProductosState,
    deleteProductoState,
    putProductoState,
    ProductoState,
    postProductoState
  }),
  composeWithDevTools(applyMiddleware(thunk))

)

